### ISSUE TITLE
Feature Request: Add 'Any Device On/Off' Condition for Zones

### ISSUE THREAD

**Issue by iFac3** [Erikvl87/nl.erikvl87.zoneactivity#1] opened 2024-09-06 05:00 UTC
Hi there,

Awesome app and effort to make Homey better. ;) Big thanks!

I’ve got few ideas what could fit into this idea behid your app. For example there is a missing condition zone card in HP23 (while it’s available in HP19). “Any light/lights on or off” Of course light is just examle here, all device type could be choosen.

It’s very useable for some scenarios.

**Comment by Erikvl87** [comment] 2024-09-06 06:39
Hi @iFac3, that's a fantastic idea! It seems like a perfect fit for the app's purpose. I will start exploring that right away.

**Comment by iFac3** [comment] 2024-09-06 06:49
It's great! 🤗

**Comment by Erikvl87** [comment] 2024-09-06 13:29
@iFac3, would something like the following flow condition be of any help?
![flow-condition-is-any-device-on](https://github.com/user-attachments/assets/7f0019b0-1309-4e38-a4e4-2007a6b299df)

**Comment by iFac3** [comment] 2024-09-06 13:35
It’s hard to understand for me, since english knowledge I have beside my native hungarian,  but seemingly okay.  :)


Kálmán Gergely
***@***.***
+36 30 743 9610

**Comment by Erikvl87** [comment] 2024-09-06 13:38
Sorry for leaving out the translation for you. It reads:

Any device of type **[[deviceType]]** in zone **[[zone]]** **[[includeDescendants]]** is on

**deviceType** is any of the available devices in your homey.
**zone** is a zone.
**includeDescendants** indicates if nested zones should be taken into account

I'll work out the details and do some more testing. Hopefully I can get this released soon.

**Comment by iFac3** [comment] 2024-09-06 14:25
This is what we need I think.


Kálmán Gergely
***@***.***
+36 30 743 9610

**Comment by Erikvl87** [comment] 2024-09-07 06:30
Version 1.2.0 has been released in the test channel! 🎉
This update introduces the new flow condition card.

Are you interested in testing it? You can access the test channel here:
https://homey.app/en-nl/app/nl.erikvl87.zoneactivity/Zone-Activity/test/

**Comment by Erikvl87** [comment] 2024-09-09 14:16
The issue is now closed as the new feature is included in the release of version 1.4.2! 🎉
https://homey.app/en-nl/app/nl.erikvl87.zoneactivity/Zone-Activity/

**Closed by Erikvl87** 2024-09-09 14:16 UTC
Labels: enhancement
