### ISSUE TITLE
Feature Request: Add Condition Cards for 'Any Sensor Value' in Zones (Above/Below/Equal)

### ISSUE THREAD

**Issue by iFac3** [Erikvl87/nl.erikvl87.zoneactivity#2] opened 2024-09-06 07:06 UTC
An other missing Zone Activity feature could be resolved by your app. This kind of condition cards: "Any sensor value is under/above" "Any sensor value is equal" (both invertable nicely) Values could come from all the listed in zone activity cards (Luminance/Temp/Hunidity/etc)

It could be an additional feature, that Zone Activity cards do not handle well.

**Comment by Erikvl87** [comment] 2024-09-06 07:43
Thank you for all the great ideas! That could definitely be valuable. I'll prioritize #1 first and then see if I can address this one afterward.

**Comment by Erikvl87** [comment] 2024-09-08 06:04
Version 1.3.0 has been released in the test channel! 🎉
This update introduces the new flow condition card.

![flow-condition-evaluate-sensor-capability](https://github.com/user-attachments/assets/fdba8cf5-cee8-475c-8c52-c6a4028b608d)

It reads: A sensor with **[[capability]]** capabilities in zone **[[zone]]** (**[[includeDescendants]]**) has a value that **[[equation]]** **[[value]]**

**capability** is any of the sensor capabilities.
**zone** is the zone you like to check.
**includeDescendants** indicates if nested zones should be taken into account.
**equation** is the equation it has to execute.
**value** is the value to test the capability against inside the given equation.

Are you interested in testing it? You can access the test channel here:
https://homey.app/en-nl/app/nl.erikvl87.zoneactivity/Zone-Activity/test/

**Comment by Erikvl87** [comment] 2024-09-09 14:15
The issue is now closed as the new feature is included in the release of version 1.4.2! 🎉
https://homey.app/en-nl/app/nl.erikvl87.zoneactivity/Zone-Activity/

**Closed by Erikvl87** 2024-09-09 14:15 UTC
Labels: enhancement
